// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzQUKF37oNROjuUlg7DgCG0VVS6qLPIHw',
    appId: '1:171454528240:web:b5784ad7b2b1a2b936e035',
    messagingSenderId: '171454528240',
    projectId: 'cars-app-99694',
    authDomain: 'cars-app-99694.firebaseapp.com',
    storageBucket: 'cars-app-99694.appspot.com',
    measurementId: 'G-FD918RKDL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWpN58HypwunpHfwjaetoPYPU9bIToGgg',
    appId: '1:171454528240:android:7c0c57164bb54b9836e035',
    messagingSenderId: '171454528240',
    projectId: 'cars-app-99694',
    storageBucket: 'cars-app-99694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD56sW7v29mAR01Y-abeg68NJJ-nr-_6OU',
    appId: '1:171454528240:ios:021bc2c23ee461d636e035',
    messagingSenderId: '171454528240',
    projectId: 'cars-app-99694',
    storageBucket: 'cars-app-99694.appspot.com',
    iosClientId: '171454528240-vl48hniv9habr27jd8thce0bt9qaa23k.apps.googleusercontent.com',
    iosBundleId: 'com.example.carsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD56sW7v29mAR01Y-abeg68NJJ-nr-_6OU',
    appId: '1:171454528240:ios:ef6de42b8c995df436e035',
    messagingSenderId: '171454528240',
    projectId: 'cars-app-99694',
    storageBucket: 'cars-app-99694.appspot.com',
    iosClientId: '171454528240-uths6bgveh82tqf8a12vtmm98ejkso8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.carsApp.RunnerTests',
  );
}
